## Import Library

In [1]:
import cv2
import numpy as np
## 202331066_M.Kahlil Ghibran

## Membaca Citra

In [2]:
citra = cv2.imread('Delima.jpg')
## 202331066_M.Kahlil Ghibran

In [12]:
cv2.imshow('Delima', citra)
cv2.waitKey()
cv2.destroyAllWindows()
## 202331066_M.Kahlil Ghibran

## Dimensi Citra

In [4]:
print(citra.shape)
print(citra.dtype)
## 202331066_M.Kahlil Ghibran

(478, 720, 3)
uint8


## Splitting Citra RGB/BGR

In [5]:
b = citra [:,:,0]
g = citra [:,:,1]
r = citra [:,:,2]
## 202331066_M.Kahlil Ghibran

## RGB to Grayscale

In [13]:
panjang = len(citra)#menghitung baris
lebar = len(citra[0])#menghitung kolom

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] #merah = 29,89% ; hijau = 58,7% ; biru = 11,41%

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow('citra grayscale', citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()
## 202331066_M.Kahlil Ghibran

In [7]:
print(citra)
## 202331066_M.Kahlil Ghibran

[[[  4   3  97]
  [  4   3  97]
  [  5   3  99]
  ...
  [ 96  81 232]
  [ 52  40 194]
  [ 63  52 208]]

 [[  3   2  96]
  [  3   2  96]
  [  4   3  97]
  ...
  [ 41  29 181]
  [ 39  31 186]
  [ 22  15 172]]

 [[  3   0  92]
  [  3   0  92]
  [  2   1  93]
  ...
  [ 14   8 163]
  [  8   4 163]
  [ 38  36 196]]

 ...

 [[115  98 209]
  [110  94 202]
  [111  95 202]
  ...
  [ 92  63 212]
  [ 87  58 208]
  [ 81  51 204]]

 [[123 109 214]
  [117 104 206]
  [115 102 204]
  ...
  [ 92  65 209]
  [ 88  60 207]
  [ 84  55 204]]

 [[126 114 214]
  [120 108 208]
  [116 106 206]
  ...
  [ 90  64 206]
  [ 88  61 205]
  [ 88  60 207]]]


In [8]:
print(citra_gray)
## 202331066_M.Kahlil Ghibran

[[ 31  31  31 ... 127  87  99]
 [ 30  30  31 ...  75  78  62]
 [ 27  27  28 ...  55  51  84]
 ...
 [133 128 128 ... 110 106 100]
 [141 135 133 ... 111 107 102]
 [145 139 137 ... 109 107 107]]


## Grayscale to Binary

In [14]:
panjang = len(citra)#menghitung baris
lebar = len(citra[0])#menghitung kolom

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih
        else:
            citra_biner[i,j] = 0 #hitam

cv2.imshow('citra binary', citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()
## 202331066_M.Kahlil Ghibran

In [10]:
print(citra_biner)
## 202331066_M.Kahlil Ghibran

[[0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [11]:
print(citra_biner[50,50])
## 202331066_M.Kahlil Ghibran

0.0
